
// Generated by https://quicktype.io

export interface IProducto {
  categoria?: string;
  cod?:       string;
  titulo?:    string;
  url?:       string;
}

// Generated by https://quicktype.io

export interface IProductoDesc {
  categoria?:  string;
  desc1?:      string;
  desc2?:      string;
  producto?:   string;
  resumen?:    string;
  subtitulo1?: string;
  subtitulo2?: string;
}
